apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    api: ""
    kubebuilder.k8s.io: 0.1.12
  name: clusters.clusterregistry.k8s.io
spec:
  group: clusterregistry.k8s.io
  names:
    kind: Cluster
    plural: clusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            kubernetesApiEndpoints:
              properties:
                caBundle:
                  format: byte
                  type: string
                serverEndpoints:
                  items:
                    properties:
                      clientCIDR:
                        type: string
                      serverAddress:
                        type: string
                    type: object
                  type: array
              type: object
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastHeartbeatTime:
                    format: date-time
                    type: string
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
