apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.clusterregistry.k8s.io
spec:
  insecureSkipTLSVerify: true
  group: clusterregistry.k8s.io
  groupPriorityMinimum: 100
  version: v1alpha1
  versionPriority: 100
  service:
    name: cr-service
    namespace: default
