#!/bin/bash

# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generates an OpenAPI 2.0 spec for the cluster registry API. Pass
# "--verify-only" as the only flag to verify the existing spec instead of
# generating a new one.
#
# Usage:
#   update-openapi-spec.sh [--verify-only]

set -euo pipefail

SCRIPT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPT_BASE=$(cd ${SCRIPT_ROOT}/../..; pwd)
REPO_DIRNAME=$(basename $(dirname "${SCRIPT_ROOT}"))
TMPDIR="$(mktemp -d /tmp/openapispecXXXXXXXX)"
SPEC_PATH=api/swagger.json

# Called on EXIT after the temporary directories are created.
function clean_up() {
  [[ -n "${CLUSTERREGISTRY_PID-}" ]] && kill "${CLUSTERREGISTRY_PID}" 1>&2 2>/dev/null

  if [[ "${TMPDIR}" == "/tmp/openapispec"* ]]; then
    rm -rf "${TMPDIR}"
  fi
}
trap clean_up EXIT

# The API server can serve the OpenAPI spec without a valid etcd endpoint.
bazel run //cmd/clusterregistry -- --etcd-servers http://invalid --secure-port 8844 --use-delegated-auth=false &
CLUSTERREGISTRY_PID=$!
sleep 5
curl -ko ${TMPDIR}/swagger.json https://localhost:8844/swagger.json

# In verify mode, take a diff and exit with failure if the diff is not empty.
if [[ ${1-} == "--verify-only" ]]; then
  ret=0
  diff -Naupr -I 'Auto generated by' "${TMPDIR}/swagger.json" "${SCRIPT_BASE}/${REPO_DIRNAME}/${SPEC_PATH}" || ret=$?
  if [[ $ret -ne 0 ]]; then
    echo "Generated OpenAPI spec is out of date. Please run hack/update-openapi-spec.sh"
    exit 1
  fi
else
  # In generate mode, copy the generated file back into the tree.
  cp "${TMPDIR}/swagger.json" "${SCRIPT_BASE}/${REPO_DIRNAME}/${SPEC_PATH}"
fi
