kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  name: also-my-cluster
  labels:
    foo: bar
spec:
  kubernetesApiEndpoints:
    serverEndpoints:
      - clientCidr: "0.0.0.0"
        serverAddress: "127.0.0.1"
